server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/floreez237/config-repo
          search-paths: licensingservice







#Classpath file based solution
#server:
#  port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:///D:/Repositories/Microservice Test/confsvr/src/main/resources/config/licensingservice